### ISSUE TITLE
Shell integration with path learning?

### ISSUE THREAD

**Issue by cig0** [ClementNerma/Jumpy#1]
Hi Clem, as the title says: is that something you may add in the future? It is super handy for me to have the _jumper_ (Zoxide, here) automatically learn my directory structure navigation habits. 
Thanks.

**Comment by ClementNerma** [comment]
Sure! What shell would you need it for?

For ZSH you can already use this snippet:

```zsh
# Jump to a directory using Jumpy
function z() {
    [[ -z $1 ]] && { echo "Please provide a query."; return 1 }

    local result=$(jumpy query "$1" --checked --after "$PWD")

    if [[ -n $result ]]; then
        export __JUMPY_DONT_REGISTER=1
        cd "$result"
        export __JUMPY_DONT_REGISTER=0
    fi
}

# Integration for Jumpy
function jumpy_handler() {
    if (( $__JUMPY_DONT_REGISTER )); then
        return
    fi

    emulate -L zsh
    jumpy inc "$PWD"
}

chpwd_functions=(${chpwd_functions[@]} "jumpy_handler")
```

**Comment by cig0** [comment]
Works wonderfully, merci beaucoup 🙌

**Comment by cig0** [comment]
Btw, a related question: how many entries does Jumpy keep by default?

**Comment by ClementNerma** [comment]
There is no limit. Even with a million directories it should sta very snappy (on an SSD at least).
